/-
Copyright (c) 2025 Runway contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import Lean
import Verso.Output.Html

/-!
# Dependency Graph Loading and Embedding

Loads SVG and JSON dependency graph files generated by Dress and embeds
them in the Blueprint HTML output with interactive controls.

## Files Expected from Dress

- `dep-graph.svg`: Visual representation of the dependency graph
- `dep-graph.json`: D3.js-compatible JSON data with layout information

## Integration

The SVG is embedded directly in the HTML with an interactive wrapper
providing pan, zoom, and navigation controls. The JSON data enables
JavaScript-based interactivity (highlighting, navigation, tooltips).
-/

namespace Runway.DepGraph

open Verso.Output Html

/-! ## File Loading -/

/-- Load the dependency graph SVG from the Dress build directory -/
def loadSvg (dressedDir : System.FilePath) : IO (Option String) := do
  let svgPath := dressedDir / "dep-graph.svg"
  if ← svgPath.pathExists then
    some <$> IO.FS.readFile svgPath
  else
    pure none

/-- Load the dependency graph JSON from the Dress build directory -/
def loadJson (dressedDir : System.FilePath) : IO (Option String) := do
  let jsonPath := dressedDir / "dep-graph.json"
  if ← jsonPath.pathExists then
    some <$> IO.FS.readFile jsonPath
  else
    pure none

/-- Load both SVG and JSON from the Dress build directory -/
def loadGraphFiles (dressedDir : System.FilePath) : IO (Option String × Option String) := do
  let svg ← loadSvg dressedDir
  let json ← loadJson dressedDir
  pure (svg, json)

/-! ## HTML Embedding -/

/-- Create the toolbar controls for the graph -/
private def graphToolbar : Html :=
  .tag "div" #[("class", "dep-graph-toolbar")] (
    .tag "button" #[("id", "graph-zoom-in"), ("title", "Zoom in"), ("aria-label", "Zoom in")]
      (.text true "+") ++
    .tag "button" #[("id", "graph-zoom-out"), ("title", "Zoom out"), ("aria-label", "Zoom out")]
      (.text true "\u2212") ++
    .tag "button" #[("id", "graph-reset"), ("title", "Reset view"), ("aria-label", "Reset view")]
      (.text true "Reset") ++
    .tag "button" #[("id", "graph-fit"), ("title", "Fit to window"), ("aria-label", "Fit to window")]
      (.text true "Fit")
  )

/-- Embed the SVG in an interactive container -/
def embedSvg (svg : String) : Html :=
  .tag "div" #[("class", "dep-graph-container")] (
    graphToolbar ++
    .tag "div" #[("class", "dep-graph-viewport"), ("id", "dep-graph-viewport")] (
      .tag "div" #[("class", "dep-graph-svg"), ("id", "dep-graph")] (
        Html.text false svg
      )
    )
  )

/-- Embed graph JSON data for JavaScript interactivity -/
def embedJsonData (json : String) : Html :=
  .tag "script" #[("type", "application/json"), ("id", "dep-graph-data")] (
    Html.text false json
  )

/-- Embed both SVG and JSON data (if available) -/
def embedGraph (svg : Option String) (json : Option String) : Html :=
  let svgHtml := match svg with
    | some s => embedSvg s
    | none => .tag "div" #[("class", "dep-graph-container"), ("id", "dep-graph")]
        (.tag "p" #[("class", "dep-graph-placeholder")]
          (.text true "Dependency graph not available. Run Dress to generate."))
  let jsonHtml := match json with
    | some j => embedJsonData j
    | none => Html.empty
  jsonHtml ++ svgHtml

/-- Create the complete graph section with header -/
def graphSection (svg : Option String) (json : Option String) : Html :=
  .tag "section" #[("class", "graph-section"), ("id", "dependency-graph")] (
    .tag "h2" #[] (.text true "Dependency Graph") ++
    embedGraph svg json
  )

end Runway.DepGraph
