/-
Copyright (c) 2025 Runway contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import Lean
import Verso.Output.Html
import Runway.Config
import Runway.Genre
import Runway.Site
import Runway.Render

/-!
# Blueprint HTML Templates

Reusable HTML template components for Blueprint site generation.
These templates can be composed to build complete pages.

## Template Types

- **Layout templates**: Full page structure (html, head, body)
- **Component templates**: Reusable UI components
- **Section templates**: Page sections (header, footer, nav)
-/

namespace Runway.Templates

open Lean (Name)
open Verso.Output Html

/-! ## Navigation Templates -/

/-- Breadcrumb navigation -/
def breadcrumbs (path : Array String) : RenderM Html := do
  if path.isEmpty then return Html.empty
  let _ ← Render.getConfig

  let crumbs := (List.range path.size).zip path.toList |>.map fun (i, segment) =>
    let href := String.join (path.toList.take (i + 1) |>.map (· ++ "/"))
    if i == path.size - 1 then
      spanClass "breadcrumb current" (Html.text true segment)
    else
      htmlLink href (Html.text true segment) (some "breadcrumb")

  return .tag "nav" #[("class", "breadcrumbs"), ("aria-label", "Breadcrumb")] (
    .tag "ol" #[] (
      .seq (crumbs.toArray.map fun crumb => .tag "li" #[] crumb)
    )
  )

/-- Table of contents for nodes on a page -/
def tableOfContents (nodes : Array NodeInfo) : Html :=
  if nodes.isEmpty then Html.empty
  else
    let items := nodes.map fun node =>
      .tag "li" #[("class", s!"toc-item status-{node.status.toCssClass}")] (
        htmlLink s!"#{node.label}" (
          spanClass "toc-env" (Html.text true node.envType) ++
          Html.text true " " ++
          Html.text true (node.title.getD node.label)
        ) none
      )

    .tag "nav" #[("class", "table-of-contents"), ("aria-label", "Table of Contents")] (
      .tag "h2" #[] (Html.text true "Contents") ++
      .tag "ol" #[] (.seq items)
    )

/-- Site navigation menu -/
def siteNav (pages : Array SitePage) (currentPath : String) : Html :=
  let items := pages.map fun page =>
    let isActive := page.path == currentPath
    let cls := if isActive then "nav-item active" else "nav-item"
    .tag "li" #[("class", cls)] (
      htmlLink page.path (Html.text true page.title) none
    )

  .tag "nav" #[("class", "site-nav"), ("aria-label", "Site Navigation")] (
    .tag "ul" #[] (.seq items)
  )

/-! ## Header Templates -/

/-- Standard page header with title and optional subtitle -/
def pageHeader (title : String) (subtitle : Option String := none) : Html :=
  .tag "header" #[("class", "page-header")] (
    .tag "h1" #[] (Html.text true title) ++
    (match subtitle with
     | some s => .tag "p" #[("class", "subtitle")] (Html.text true s)
     | none => Html.empty)
  )

/-- Site header with branding and nav -/
def siteHeader (config : Config) : Html :=
  .tag "header" #[("class", "site-header")] (
    divClass "header-brand" (
      htmlLink "/" (Html.text true config.title) (some "site-title")
    ) ++
    divClass "header-links" (
      (match config.githubUrl with
       | some url => htmlLink url (Html.text true "GitHub") (some "header-link")
       | none => Html.empty) ++
      (match config.docgen4Url with
       | some url => htmlLink url (Html.text true "Documentation") (some "header-link")
       | none => Html.empty)
    )
  )

/-! ## Footer Templates -/

/-- Standard page footer -/
def pageFooter (config : Config) : Html :=
  .tag "footer" #[("class", "page-footer")] (
    divClass "footer-content" (
      .tag "p" #[] (
        Html.text true "Generated by " ++
        htmlLink "https://github.com/leanprover-community/runway" (Html.text true "Runway") none
      ) ++
      (match config.githubUrl with
       | some url => .tag "p" #[] (htmlLink url (Html.text true "View source on GitHub") none)
       | none => Html.empty)
    )
  )

/-! ## Status Badge Templates -/

/-- Status badge for a node -/
def statusBadge (status : Graph.NodeStatus) : Html :=
  let (cls, label) := match status with
    | .notReady => ("badge-not-ready", "Not Ready")
    | .stated => ("badge-stated", "Stated")
    | .ready => ("badge-ready", "Ready")
    | .sorry => ("badge-sorry", "Has Sorry")
    | .proven => ("badge-proven", "Proven")
    | .fullyProven => ("badge-fully-proven", "Fully Proven")
    | .mathlibReady => ("badge-mathlib-ready", "Mathlib Ready")
    | .inMathlib => ("badge-in-mathlib", "In Mathlib")
  spanClass s!"status-badge {cls}" (Html.text true label)

/-- Compact status indicator (colored dot) -/
def statusDot (status : Graph.NodeStatus) : Html :=
  .tag "span" #[
    ("class", s!"status-dot status-{status.toCssClass}"),
    ("title", status.toDisplayString),
    ("aria-label", s!"Status: {status.toDisplayString}")
  ] Html.empty

/-! ## Card Templates -/

/-- Node summary card (for index pages) -/
def nodeCard (node : NodeInfo) : Html :=
  .tag "article" #[("class", s!"node-card status-{node.status.toCssClass}")] (
    divClass "card-header" (
      spanClass "card-env" (Html.text true node.envType.capitalize) ++
      statusDot node.status
    ) ++
    divClass "card-body" (
      .tag "h3" #[("class", "card-title")] (
        htmlLink s!"#{node.label}" (Html.text true (node.title.getD node.label)) none
      ) ++
      (if node.statementHtml.length > 200 then
        divClass "card-preview" (Html.text false (String.ofList (node.statementHtml.toList.take 200) ++ "..."))
       else
        divClass "card-preview" (Html.text false node.statementHtml))
    ) ++
    divClass "card-footer" (
      (if node.declNames.isEmpty then Html.empty
       else spanClass "card-decls" (Html.text true s!"{node.declNames.size} declarations")) ++
      (if node.uses.isEmpty then Html.empty
       else spanClass "card-deps" (Html.text true s!"{node.uses.size} dependencies"))
    )
  )

/-- Grid of node cards -/
def nodeCardGrid (nodes : Array NodeInfo) : Html :=
  divClass "node-card-grid" (
    .seq (nodes.map nodeCard)
  )

/-! ## Progress Templates -/

/-- Detailed progress breakdown by environment type -/
def progressByType (site : BlueprintSite) : Html :=
  let envTypes := site.nodes.map (·.envType) |>.toList.eraseDups

  let rows := envTypes.map fun envType =>
    let nodesOfType := site.nodesByEnvType envType
    let proven := nodesOfType.filter fun n => n.status == .proven || n.status == .fullyProven
    let mathlib := nodesOfType.filter fun n => n.status == .mathlibReady || n.status == .inMathlib
    let total := nodesOfType.size
    let completed := proven.size + mathlib.size
    let pct := if total == 0 then 0.0 else (completed.toFloat / total.toFloat) * 100.0

    .tag "tr" #[] (
      .tag "td" #[] (Html.text true envType.capitalize) ++
      .tag "td" #[] (Html.text true s!"{proven.size}") ++
      .tag "td" #[] (Html.text true s!"{mathlib.size}") ++
      .tag "td" #[] (Html.text true s!"{total}") ++
      .tag "td" #[] (
        divClass "mini-progress" (
          .tag "div" #[("class", "mini-fill"), ("style", s!"width: {pct}%")] Html.empty
        )
      )
    )

  .tag "table" #[("class", "progress-table")] (
    .tag "thead" #[] (
      .tag "tr" #[] (
        .tag "th" #[] (Html.text true "Type") ++
        .tag "th" #[] (Html.text true "Proved") ++
        .tag "th" #[] (Html.text true "Mathlib") ++
        .tag "th" #[] (Html.text true "Total") ++
        .tag "th" #[] (Html.text true "Progress")
      )
    ) ++
    .tag "tbody" #[] (.seq rows.toArray)
  )

/-- Completion percentage as styled text -/
def completionText (site : BlueprintSite) : Html :=
  let pct := site.completionPercentage
  let cls := if pct >= 90 then "completion-high"
    else if pct >= 50 then "completion-medium"
    else "completion-low"
  spanClass s!"completion-text {cls}" (
    Html.text true s!"{pct.toString}% complete"
  )

/-! ## Alert/Notice Templates -/

/-- Information notice -/
def notice (content : Html) (kind : String := "info") : Html :=
  divClass s!"notice notice-{kind}" content

/-- Warning notice -/
def warning (content : Html) : Html :=
  notice content "warning"

/-- Error notice -/
def errorNotice (content : Html) : Html :=
  notice content "error"

/-- Success notice -/
def success (content : Html) : Html :=
  notice content "success"

/-! ## Metadata Templates -/

/-- Node metadata section -/
def nodeMetadata (node : NodeInfo) : RenderM Html := do
  let config ← Render.getConfig

  let declSection ← if node.declNames.isEmpty then pure Html.empty
    else do
      let links := node.declNames.map fun name =>
        let nameStr := name.toString
        match config.docgen4Url with
        | some baseUrl =>
          let url := s!"{baseUrl}{nameStr.replace "." "/"}.html"
          htmlLink url (Html.text true nameStr) (some "decl-link")
        | none =>
          spanClass "decl-name" (Html.text true nameStr)
      pure <| .tag "div" #[("class", "meta-section decls")] (
        .tag "h4" #[] (Html.text true "Lean Declarations") ++
        .tag "ul" #[] (.seq (links.map fun l => .tag "li" #[] l))
      )

  let depSection := if node.uses.isEmpty then Html.empty
    else
      let links := node.uses.map fun label =>
        htmlLink s!"#{label}" (Html.text true label) (some "dep-link")
      .tag "div" #[("class", "meta-section deps")] (
        .tag "h4" #[] (Html.text true "Dependencies") ++
        .tag "ul" #[] (.seq (links.map fun l => .tag "li" #[] l))
      )

  return divClass "node-metadata" (declSection ++ depSection)

/-! ## Search Templates -/

/-- Search input box -/
def searchBox (placeholder : String := "Search...") : Html :=
  .tag "div" #[("class", "search-box")] (
    .tag "input" #[
      ("type", "search"),
      ("id", "node-search"),
      ("placeholder", placeholder),
      ("aria-label", "Search nodes")
    ] Html.empty ++
    .tag "button" #[("type", "button"), ("id", "search-btn")] (Html.text true "Search")
  )

/-- Filter controls for node list -/
def nodeFilters : Html :=
  divClass "node-filters" (
    .tag "label" #[] (
      Html.text true "Status: " ++
      .tag "select" #[("id", "filter-status")] (
        .tag "option" #[("value", "all")] (Html.text true "All") ++
        .tag "option" #[("value", "proved")] (Html.text true "Proved") ++
        .tag "option" #[("value", "mathlib-ok")] (Html.text true "Mathlib") ++
        .tag "option" #[("value", "stated")] (Html.text true "Stated") ++
        .tag "option" #[("value", "not-ready")] (Html.text true "Not Ready")
      )
    ) ++
    .tag "label" #[] (
      Html.text true "Type: " ++
      .tag "select" #[("id", "filter-type")] (
        .tag "option" #[("value", "all")] (Html.text true "All")
        -- Additional options populated by JavaScript
      )
    )
  )

end Runway.Templates
